services:
    app:
        image: nfdi4chem/coconut:dev-app-latest
        container_name: coconut_app
        networks:
            - coconut
        depends_on:
            - pgsql
            - redis
            - cm
            # - typesense
        volumes:
            - www-data:/var/www
    worker:
        image: nfdi4chem/coconut:dev-app-latest
        command: php artisan horizon
        container_name: coconut_worker
        networks:
            - coconut
        depends_on:
            - pgsql
            - redis
            - cm
            # - typesense
        volumes:
            - www-data:/var/www
    pgsql:
        image: "informaticsmatters/rdkit-cartridge-debian:latest"
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'coconut-pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - coconut
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'coconut-redis:/data'
        networks:
            - coconut
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    nginx:
        build:
            context: .
            dockerfile: ./resources/dc-ops/nginx/Dockerfile
        container_name: coconut_nginx
        restart: unless-stopped
        ports:
            - 80:80
        networks:
            - coconut
        depends_on:
            - app
        volumes:
            - www-data:/var/www
    cm:
        image: "nfdi4chem/cheminformatics-microservice:dev-latest"
        environment:
            HOMEPAGE_URL:  "https://docs.api.naturalproducts.net"
        ports:
            - "81:80"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:81/latest/chem/health"]
            interval: 1m30s
            timeout: 10s
            retries: 20
            start_period: 60s
        networks:
            - coconut
    # typesense:
    #     image: 'typesense/typesense:0.25.2'
    #     ports:
    #         - '${FORWARD_TYPESENSE_PORT:-8108}:8108'
    #     environment:
    #         TYPESENSE_DATA_DIR: '${TYPESENSE_DATA_DIR:-/typesense-data}'
    #         TYPESENSE_API_KEY: '${TYPESENSE_API_KEY:-xyz}'
    #         TYPESENSE_ENABLE_CORS: '${TYPESENSE_ENABLE_CORS:-true}'
    #     volumes:
    #         - 'coconut-typesense:/typesense-data'
    #     networks:
    #         - coconut
    #     healthcheck:
    #         test:
    #             - CMD
    #             - wget
    #             - '--no-verbose'
    #             - '--spider'
    #             - 'http://localhost:8108/health'
    #         retries: 5
    #         timeout: 7s
networks:
    coconut:
        driver: bridge
volumes:
    coconut-pgsql:
        driver: local
    coconut-redis:
        driver: local
    www-data:
        driver: local
    # coconut-typesense:
    #     driver: local
