name: Feature Request Template
description: >-
  Use this template to submit a feature request. Provide detailed information
  about the feature you would like to see implemented. For urgent issues or
  questions, please contact us directly.
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Give your feature request a descriptive title.
      placeholder: 'Feature Title'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Provide a detailed description of the feature you would like to see
        implemented. Explain how it would enhance the product and benefit
        the users. Feel free to include any specific use cases or scenarios.
      placeholder: 'Describe the feature in detail'
    validations:
      required: true

  - type: textarea
    id: potential-benefits
    attributes:
      label: Potential Benefits
      description: >-
        Describe the potential benefits or positive outcomes that implementing
        this feature could bring. How would it improve user experience,
        productivity, or any other aspect?
      placeholder: 'Describe the benefits'
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: >-
        If applicable, provide a specific use case or scenario where this feature
        would be particularly useful. This can help us better understand the
        practical application of the feature.
      placeholder: 'Provide a specific use case'
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: >-
        Include any additional information, ideas, or suggestions related to
        your feature request. This could include references to similar features
        in other products, related research, or any other relevant details.
      placeholder: 'Any additional information or suggestions'
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Indicate the priority level for your feature request.
      multiple: false
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: >-
        Describe the potential impact of implementing this feature on your
        workflow or the overall product experience.
      placeholder: 'Describe the impact'
    validations:
      required: true

  - type: input
    id: contact-info
    attributes:
      label: Contact Information
      description: >-
        If you would like to be contacted regarding your feature request,
        please provide your preferred contact information (e.g., email address).
      placeholder: 'Your contact information (optional)'
    validations:
      required: false
